# Generated by Django 3.2.6 on 2024-07-16 15:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Administrator')], max_length=30, verbose_name='role')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='avatar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
